# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.
encoding: utf-8
# Site settings
title: Archer
brief-intro: stay hungry stay foolish
baseurl: '' # the subpath of your site, e.g. /blog
url: 'https://tangheng1995.github.io' # the base hostname & protocol for your site

permalink: /:year/:month/:day/:title/

# other links
twitter_username:
facebook_username:
github_username: tangheng1995
email: 347420070@qq.com
weibo_username: saymololy
zhihu_username: saymololy
linkedIn_username:
dribbble_username:

description_footer: 本站记录我成长之路的点点滴滴！

# comments
# 三种评论插件，选一个就好了
disqus_shortname: #lework
gitalk:
  enable: false
  clientID: aa4ee6a59f0cfd9ed9b2
  clientSecret: 617a322486aa0d38fbee4b5dddb62f9c92c58ee2
  repo: https://github.com/tangheng1995/Comments
  owner: tangheng1995
  admin: tangheng1995
utteranc_es:
  enable: true
  repo: 'tangheng1995/tangheng1995.github.io'
  issue-term: pathname
  theme: github-light

# 赞赏
reward:
  enable: true
  wechat: /assets/images/reward/wechat.png
  alipay: /assets/images/reward/alipay.png

# statistic analysis 统计代码
# 百度统计 id，将统计代码替换为自己的百度统计id，即
# hm.src = "//hm.baidu.com/hm.js?xxxxxxxxxxxx";
# xxxxx字符串
baidu_tongji_id: 23fa40cf36cb3e7226dea6957fdacb23
google_analytics_id:

# Build settings
markdown: kramdown

kramdown:
  input: GFM
  syntax_highlighter: rouge

# port
# port: 1234

# url
category_dir: category/
tag_dir: tag/

# excerpt
excerpt_separator: "\n\n\n\n"

# paginate
plugins: [jekyll-paginate]
paginate: 10

exclude: ["README.md", "LICENSE", ".post-template", ".gitignore", "start.bat"]

